services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/front
    command: sh -c "cd front && npm run dev"
    # command: sh -c "cd front && npm run build && npm start"
    tty: true
